name: Build and Deploy BAR File

on:
  push:
    branches:
      - main

jobs:
  build-bar:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up ACE runtime environment
      - name: Set up ACE
        run: |
          sudo apt-get update
          sudo apt-get install -y ibm-ace

      # Build the BAR file
      - name: Build BAR File
        run: |
          mqsipackagebar -w . -a STAT_LIBproject.generated.bar -k MyApplication

      # Upload the BAR file as an artifact
      - name: Upload BAR File
        uses: actions/upload-artifact@v3
        with:
          name: STAT_LIBproject.generated.bar
          path: ./STAT_LIBproject.generated.bar

